package com.archlytics.report;

import com.archlytics.ai.AiAnalysisResult;
import com.archlytics.graph.DependencyGraph;
import com.archlytics.graph.GraphMetrics;
import com.archlytics.rules.Violation;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.Set;

public final class HtmlReport {

  private HtmlReport() {}

  public static String render(
      String repoPath,
      int fileCount,
      DependencyGraph graph,
      GraphMetrics.Metrics metrics,
      List<Violation> violations,
      ArchitectureDiagrams diagrams,
      HealthScore healthScore,
      AiAnalysisResult ai) {
    return renderInternal(
        repoPath, fileCount, graph, metrics, violations, diagrams, healthScore, ai, false);
  }

  public static String renderWithoutAi(
      String repoPath,
      int fileCount,
      DependencyGraph graph,
      GraphMetrics.Metrics metrics,
      List<Violation> violations,
      ArchitectureDiagrams diagrams,
      HealthScore healthScore) {
    return renderInternal(
        repoPath, fileCount, graph, metrics, violations, diagrams, healthScore, null, true);
  }

  private static String renderInternal(
      String repoPath,
      int fileCount,
      DependencyGraph graph,
      GraphMetrics.Metrics metrics,
      List<Violation> violations,
      ArchitectureDiagrams diagrams,
      HealthScore healthScore,
      AiAnalysisResult ai,
      boolean skipAi) {
    String generated =
        LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));

    StringBuilder html = new StringBuilder();
    html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.append("<meta charset=\"UTF-8\">\n");
    html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.append("<title>Archlytics Report</title>\n");
    html.append("<script src=\"https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js\"></script>\n");
    html.append("<style>").append(styles()).append("</style>\n");
    html.append("</head>\n<body>\n");
    html.append("<div class=\"container\">\n");

    html.append("<header class=\"header\">\n");
    html.append("<div>\n");
    html.append("<h1>Archlytics Architecture Report</h1>\n");
    html.append("<p class=\"meta\">Repository: <code>").append(escape(repoPath)).append("</code></p>\n");
    html.append("<p class=\"meta\">Generated: ").append(escape(generated)).append("</p>\n");
    html.append("</div>\n");
    html.append("<button class=\"print-btn no-print\" onclick=\"window.print()\">Print / Save PDF</button>\n");
    html.append("</header>\n");

    appendHealthDashboard(html, healthScore, fileCount, graph.modules().size(), violations.size());

    if (skipAi) {
      html.append("<section class=\"card notice\"><p>AI analysis skipped. Deterministic analysis only.</p></section>\n");
    } else if (ai != null) {
      html.append("<section class=\"card\">\n");
      html.append("<h2>Summary</h2>\n");
      html.append("<p class=\"architecture-type\">").append(escape(ai.architectureType())).append("</p>\n");
      html.append("<p>").append(escape(ai.summary())).append("</p>\n");
      html.append("</section>\n");
    }

    appendMetrics(html, metrics, graph);
    appendModuleDependencies(html, graph);
    appendViolations(html, violations);
    appendSystemDesign(html, violations, ai);
    appendScaling(html, ai);
    appendRecommendations(html, ai);
    appendDiagrams(html, diagrams, ai);

    html.append("<footer class=\"footer\">Generated by Archlytics</footer>\n");
    html.append("</div>\n");
    html.append("<script>mermaid.initialize({ startOnLoad: true, theme: 'neutral' });</script>\n");
    html.append("</body>\n</html>");

    return html.toString();
  }

  private static void appendHealthDashboard(
      StringBuilder html,
      HealthScore healthScore,
      int fileCount,
      int moduleCount,
      int violationCount) {
    String scoreClass = scoreClass(healthScore.score());

    html.append("<section class=\"dashboard\">\n");
    html.append("<div class=\"score-card ").append(scoreClass).append("\">\n");
    html.append("<div class=\"score-value\">").append(healthScore.score()).append("</div>\n");
    html.append("<div class=\"score-label\">/ 100 — ").append(escape(healthScore.label())).append("</div>\n");
    html.append("</div>\n");

    html.append("<div class=\"stat-grid\">\n");
    appendStat(html, "Java files", String.valueOf(fileCount));
    appendStat(html, "Modules", String.valueOf(moduleCount));
    appendStat(html, "Violations", String.valueOf(violationCount));
    html.append("</div>\n");

    if (!healthScore.topRisks().isEmpty()) {
      html.append("<div class=\"top-risks\">\n<h3>Top risks</h3><ol>\n");
      for (String risk : healthScore.topRisks()) {
        html.append("<li>").append(escape(risk)).append("</li>\n");
      }
      html.append("</ol></div>\n");
    }

    html.append("</section>\n");
  }

  private static void appendStat(StringBuilder html, String label, String value) {
    html.append("<div class=\"stat\"><div class=\"stat-value\">")
        .append(escape(value))
        .append("</div><div class=\"stat-label\">")
        .append(escape(label))
        .append("</div></div>\n");
  }

  private static void appendMetrics(
      StringBuilder html, GraphMetrics.Metrics metrics, DependencyGraph graph) {
    html.append("<section class=\"card\"><h2>Graph Metrics</h2><ul>\n");
    html.append("<li><strong>Longest chain:</strong> ")
        .append(
            escape(
                metrics.longestChain().isEmpty()
                    ? "none"
                    : String.join(" → ", metrics.longestChain())))
        .append("</li>\n");
    html.append("<li><strong>Entry points:</strong> ")
        .append(
            escape(
                metrics.entryPoints().isEmpty()
                    ? "none"
                    : String.join(", ", metrics.entryPoints())))
        .append("</li>\n");
    html.append("<li><strong>Shared-kernel hubs:</strong> ")
        .append(
            escape(
                metrics.hubModules().isEmpty() ? "none" : String.join(", ", metrics.hubModules())))
        .append("</li>\n");
    html.append("<li><strong>Layer bypasses:</strong> ")
        .append(
            escape(
                GraphMetrics.findLayerBypasses(graph).isEmpty()
                    ? "none"
                    : String.join("; ", GraphMetrics.findLayerBypasses(graph))))
        .append("</li>\n");
    html.append("</ul></section>\n");
  }

  private static void appendModuleDependencies(StringBuilder html, DependencyGraph graph) {
    html.append("<section class=\"card\"><h2>Module Dependencies</h2><ul>\n");
    for (Map.Entry<String, Set<String>> entry : graph.moduleDependencies().entrySet()) {
      if (!entry.getValue().isEmpty()) {
        html.append("<li><strong>")
            .append(escape(entry.getKey()))
            .append("</strong> → ")
            .append(escape(String.join(", ", entry.getValue())))
            .append("</li>\n");
      }
    }
    html.append("</ul></section>\n");
  }

  private static void appendViolations(StringBuilder html, List<Violation> violations) {
    html.append("<section class=\"card\"><h2>Violations</h2>\n");
    if (violations.isEmpty()) {
      html.append("<p class=\"muted\">No violations detected.</p>\n");
    } else {
      html.append("<div class=\"violations\">\n");
      for (Violation violation : violations) {
        html.append("<div class=\"violation\">");
        html.append("<span class=\"badge badge-")
            .append(violation.severity().name().toLowerCase())
            .append("\">")
            .append(violation.severity())
            .append("</span> ");
        html.append("<strong>").append(escape(violation.title())).append("</strong>");
        html.append("<p>").append(escape(violation.evidence())).append("</p>");
        html.append("<p class=\"rule\">rule: ").append(escape(violation.rule())).append("</p>");
        html.append("</div>\n");
      }
      html.append("</div>\n");
    }
    html.append("</section>\n");
  }

  private static void appendSystemDesign(
      StringBuilder html, List<Violation> violations, AiAnalysisResult ai) {
    html.append("<section class=\"card\"><h2>System Design Issues</h2>\n");

    List<Violation> structural =
        violations.stream().filter(v -> "system-design".equals(v.rule())).toList();

    if (!structural.isEmpty()) {
      html.append("<h3>From graph analysis</h3><ul>\n");
      for (Violation violation : structural) {
        html.append("<li><span class=\"badge badge-")
            .append(violation.severity().name().toLowerCase())
            .append("\">")
            .append(violation.severity())
            .append("</span> <strong>")
            .append(escape(violation.title()))
            .append("</strong> — ")
            .append(escape(violation.evidence()))
            .append("</li>\n");
      }
      html.append("</ul>\n");
    }

    if (ai != null && !ai.systemDesignIssues().isEmpty()) {
      html.append("<h3>From AI interpretation</h3><ul>\n");
      for (AiAnalysisResult.SystemDesignIssue issue : ai.systemDesignIssues()) {
        html.append("<li><span class=\"badge\">")
            .append(escape(issue.impact()))
            .append("</span> <strong>")
            .append(escape(issue.title()))
            .append("</strong> — ")
            .append(escape(issue.detail()))
            .append("</li>\n");
      }
      html.append("</ul>\n");
    } else if (structural.isEmpty()) {
      html.append("<p class=\"muted\">No major structural issues detected.</p>\n");
    }

    html.append("</section>\n");
  }

  private static void appendScaling(StringBuilder html, AiAnalysisResult ai) {
    html.append("<section class=\"card\"><h2>Scaling &amp; Bottleneck Analysis</h2>\n");
    if (ai == null || ai.scalingRisks().isEmpty()) {
      html.append("<p class=\"muted\">Run without --skip-ai for AI scaling predictions.</p>\n");
    } else {
      for (AiAnalysisResult.ScalingRisk risk : ai.scalingRisks()) {
        html.append("<div class=\"risk-card\">\n");
        html.append("<h3>").append(escape(risk.scenario())).append("</h3>\n");
        html.append("<p><strong>Risk:</strong> ").append(escape(risk.risk())).append("</p>\n");
        html.append("<p><strong>Mitigation:</strong> ").append(escape(risk.mitigation())).append("</p>\n");
        html.append("</div>\n");
      }
    }
    html.append("</section>\n");
  }

  private static void appendRecommendations(StringBuilder html, AiAnalysisResult ai) {
    if (ai == null || ai.recommendations().isEmpty()) {
      return;
    }

    html.append("<section class=\"card\"><h2>AI Recommendations</h2>\n");
    for (AiAnalysisResult.Recommendation rec : ai.recommendations()) {
      html.append("<div class=\"rec-card\">\n");
      html.append("<h3>").append(escape(rec.title())).append("</h3>\n");
      html.append("<p>").append(escape(rec.detail())).append("</p>\n");
      html.append("</div>\n");
    }
    html.append("</section>\n");
  }

  private static void appendDiagrams(
      StringBuilder html, ArchitectureDiagrams diagrams, AiAnalysisResult ai) {
    html.append("<section class=\"card\"><h2>Architecture Diagrams</h2>\n");
    appendDiagram(html, "Module Dependencies", diagrams.moduleDependency());
    appendDiagram(html, "Layer View", diagrams.layerView());
    appendDiagram(html, "Critical Path", diagrams.criticalPath());
    if (ai != null && ai.mermaidDiagram() != null && !ai.mermaidDiagram().isBlank()) {
      appendDiagram(html, "AI-Generated View", ai.mermaidDiagram());
    }
    html.append("</section>\n");
  }

  private static void appendDiagram(StringBuilder html, String title, String mermaid) {
    html.append("<div class=\"diagram-block\">\n");
    html.append("<h3>").append(escape(title)).append("</h3>\n");
    html.append("<pre class=\"mermaid\">").append(mermaid).append("</pre>\n");
    html.append("</div>\n");
  }

  static String scoreClass(int score) {
    if (score >= 80) {
      return "score-healthy";
    }
    if (score >= 60) {
      return "score-warning";
    }
    return "score-critical";
  }

  static String escape(String value) {
    if (value == null) {
      return "";
    }
    return value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;");
  }

  private static String styles() {
    return """
        :root {
          --bg: #0f1419;
          --card: #1a2332;
          --text: #e6edf3;
          --muted: #8b949e;
          --border: #30363d;
          --healthy: #3fb950;
          --warning: #d29922;
          --critical: #f85149;
          --high: #f85149;
          --medium: #d29922;
          --low: #58a6ff;
          --accent: #58a6ff;
        }
        * { box-sizing: border-box; }
        body {
          margin: 0;
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          background: var(--bg);
          color: var(--text);
          line-height: 1.6;
        }
        .container { max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          gap: 1rem;
          margin-bottom: 2rem;
        }
        h1 { margin: 0 0 0.5rem; font-size: 1.75rem; }
        h2 { margin-top: 0; font-size: 1.25rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
        h3 { font-size: 1rem; margin-bottom: 0.5rem; }
        .meta { color: var(--muted); margin: 0.25rem 0; font-size: 0.9rem; }
        code { background: #21262d; padding: 0.15rem 0.4rem; border-radius: 4px; font-size: 0.85rem; }
        .print-btn {
          background: var(--accent);
          color: #fff;
          border: none;
          padding: 0.6rem 1rem;
          border-radius: 8px;
          cursor: pointer;
          font-weight: 600;
          white-space: nowrap;
        }
        .print-btn:hover { opacity: 0.9; }
        .dashboard {
          display: grid;
          gap: 1rem;
          margin-bottom: 1.5rem;
        }
        .score-card {
          background: var(--card);
          border: 1px solid var(--border);
          border-radius: 12px;
          padding: 1.5rem;
          text-align: center;
        }
        .score-value { font-size: 3.5rem; font-weight: 700; line-height: 1; }
        .score-label { color: var(--muted); margin-top: 0.5rem; }
        .score-healthy .score-value { color: var(--healthy); }
        .score-warning .score-value { color: var(--warning); }
        .score-critical .score-value { color: var(--critical); }
        .stat-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 1rem;
        }
        .stat {
          background: var(--card);
          border: 1px solid var(--border);
          border-radius: 10px;
          padding: 1rem;
          text-align: center;
        }
        .stat-value { font-size: 1.5rem; font-weight: 700; }
        .stat-label { color: var(--muted); font-size: 0.85rem; }
        .top-risks {
          background: var(--card);
          border: 1px solid var(--border);
          border-radius: 10px;
          padding: 1rem 1.25rem;
        }
        .top-risks ol { margin: 0.5rem 0 0; padding-left: 1.25rem; }
        .card {
          background: var(--card);
          border: 1px solid var(--border);
          border-radius: 12px;
          padding: 1.25rem 1.5rem;
          margin-bottom: 1.25rem;
        }
        .notice { border-color: var(--warning); }
        .architecture-type {
          font-weight: 600;
          color: var(--accent);
          margin-bottom: 0.75rem;
        }
        .muted { color: var(--muted); }
        .violations { display: grid; gap: 0.75rem; }
        .violation {
          background: #161b22;
          border: 1px solid var(--border);
          border-radius: 8px;
          padding: 0.75rem 1rem;
        }
        .violation p { margin: 0.35rem 0 0; }
        .rule { color: var(--muted); font-size: 0.85rem; }
        .badge {
          display: inline-block;
          padding: 0.15rem 0.5rem;
          border-radius: 999px;
          font-size: 0.75rem;
          font-weight: 700;
          letter-spacing: 0.02em;
        }
        .badge-high { background: rgba(248,81,73,0.15); color: var(--high); }
        .badge-medium { background: rgba(210,153,34,0.15); color: var(--medium); }
        .badge-low { background: rgba(88,166,255,0.15); color: var(--low); }
        .risk-card, .rec-card {
          background: #161b22;
          border: 1px solid var(--border);
          border-radius: 8px;
          padding: 0.75rem 1rem;
          margin-bottom: 0.75rem;
        }
        .diagram-block {
          background: #fff;
          border-radius: 8px;
          padding: 1rem;
          margin-bottom: 1rem;
          overflow-x: auto;
        }
        .diagram-block h3 { color: #24292f; }
        .footer {
          text-align: center;
          color: var(--muted);
          font-size: 0.85rem;
          margin-top: 2rem;
        }
        @media print {
          .no-print { display: none !important; }
          body { background: #fff; color: #000; }
          .card, .score-card, .stat, .top-risks, .violation, .risk-card, .rec-card {
            background: #fff;
            border-color: #ccc;
            break-inside: avoid;
          }
          .score-healthy .score-value, .score-warning .score-value, .score-critical .score-value {
            color: #000;
          }
        }
        """;
  }
}
