package com.archlytics.report;

import com.archlytics.pr.PullRequestAnalysis;
import com.archlytics.rules.Violation;
import java.util.List;

public final class PrCommentFormatter {

  private PrCommentFormatter() {}

  public static String render(HealthScore healthScore, PullRequestAnalysis pr) {
    StringBuilder md = new StringBuilder();
    md.append("## Archlytics Report\n\n");
    md.append("**Architecture health:** ")
        .append(healthScore.score())
        .append("/100 — ")
        .append(healthScore.label());

    if (pr.violationComparison() != null) {
      md.append(" (").append(pr.violationComparison().scoreSummary()).append(")");
    }
    md.append("\n\n");

    md.append("**Changed Java files:** ").append(pr.changedFiles().size()).append("\n\n");

    List<Violation> introduced = pr.introducedViolations();
    if (introduced.isEmpty()) {
      md.append("_No new architecture violations introduced in this PR._\n\n");
    } else {
      md.append("| Severity | New in this PR |\n");
      md.append("|----------|----------------|\n");
      for (Violation violation : introduced) {
        md.append("| ")
            .append(violation.severity())
            .append(" | ")
            .append(violation.title())
            .append(" — ")
            .append(violation.evidence())
            .append(" |\n");
      }
      md.append("\n");
    }

    if (!pr.newModuleEdges().isEmpty()) {
      md.append("**New module dependencies:**\n\n");
      for (String edge : pr.newModuleEdges()) {
        md.append("- ").append(edge).append("\n");
      }
      md.append("\n");
    }

    md.append(
        "_Generated by [Archlytics](https://github.com/Hamza-spc/Archlytics) — deterministic architecture analysis for Java._\n");
    return md.toString();
  }
}
